# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://robtheoceanographer.github.io/objver/"

git_url = "https://github.com/robtheoceanographer/objver/tree/master/"

def custom_doc_links(name): return None
